FROM python:3
# ENV PYTHONUNBUFFERED=1

#Code Directory is in /code folder
WORKDIR /code 

COPY requirements.txt /code/

#Installs pip requirements in the environment
RUN pip install -r requirements.txt

COPY . /code/
