version: '3'
services:
  postgres-database: #This is the name of the Container
    image: 'postgres'
    ports:
      - '5432'
    networks:
      some_network:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django-server:
    build:
      context: .
      dockerfile: Dockerfile.dev

    restart: always
    command:  
      sh -c "
      python manage.py runserver 0.0.0.0:8000"
    ports: #Mapping of ports of the current django image/container
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - postgres-database
    links:
      - postgres-database:postgres-database
    networks:
      some_network:
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - .:/code
    command: ["pytest"]

networks:
  some_network: