# Generated by Django 3.0.4 on 2020-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='targetName',
            field=models.CharField(default='none', max_length=40),
        ),
    ]
