# Generated by Django 3.0.4 on 2020-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0002_target_targetname'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=60)),
                ('projectOwner', models.CharField(max_length=40)),
                ('projectValue', models.IntegerField(default=1)),
                ('projectStatus', models.CharField(default='Completed', max_length=20)),
                ('projectSector', models.CharField(default='other', max_length=40)),
            ],
        ),
    ]
