# Generated by Django 3.0.4 on 2020-04-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('ownerID', models.AutoField(primary_key=True, serialize=False)),
                ('ownerName', models.TextField(max_length=50)),
                ('ownerReference', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sector',
            fields=[
                ('sectorID', models.AutoField(primary_key=True, serialize=False)),
                ('sectorName', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing')], default='Completed', max_length=20),
        ),
    ]
