# Generated by Django 3.0.4 on 2020-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0004_auto_20200423_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectImage',
            field=models.FilePathField(blank=True, default='File not uploaded at entry', path='C:\\Users\\hp\\PycharmProjects\\tryTwo\\tryTwo\\projects'),
        ),
    ]
