# Generated by Django 3.0.4 on 2020-06-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0005_project_projectimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='target',
        ),
        migrations.AlterField(
            model_name='project',
            name='projectImage',
            field=models.FilePathField(blank=True, default='File not uploaded at entry', path='C:\\Users\\hp\\PycharmProjects\\tryTwo\\tryTwo\\media/projects'),
        ),
    ]
