# Generated by Django 3.0.4 on 2020-05-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectManagement', '0004_auto_20200423_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeOfInvoice',
            fields=[
                ('typeID', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('invoiceAmount', models.IntegerField()),
                ('invoiceType', models.CharField(default='', max_length=50)),
                ('invoiceDate', models.DateField()),
                ('invoiceStatus', models.CharField(default='Completed', max_length=40)),
                ('invoiceDetails', models.TextField(max_length=300)),
                ('invoiceAttachment', models.ImageField(default='', upload_to='invoices/images')),
                ('invoiceExtraWorkBoolean', models.CharField(default='False', max_length=10)),
                ('invoiceRemainingAmount', models.IntegerField(default=0)),
                ('invoiceRemainingStatus', models.TextField(default='used', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManagement.project')),
            ],
        ),
    ]
