# Generated by Django 3.0.4 on 2020-05-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceRemainingStatus',
            field=models.TextField(default='remaining', max_length=50),
        ),
    ]
