# Generated by Django 3.0.4 on 2020-06-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceManagement', '0002_auto_20200526_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceExtraWorkBoolean',
            field=models.BooleanField(default='False'),
        ),
    ]
