# Generated by Django 3.0.4 on 2020-06-13 02:11

from django.db import migrations, models
import invoiceManagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceManagement', '0003_auto_20200608_0800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='typeOfInvoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceRemainingAmount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceRemainingStatus',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceAttachment',
            field=models.FilePathField(default='File not uploaded at entry', path=invoiceManagement.models.invoice.invoice_path),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceDetails',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceExtraWorkBoolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceStatus',
            field=models.CharField(default='paid', max_length=50),
        ),
    ]
