# Generated by Django 3.0.4 on 2020-06-13 02:27

from django.db import migrations, models
import invoiceManagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceManagement', '0004_auto_20200613_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceAttachment',
            field=models.FilePathField(blank=True, default='File not uploaded at entry', path=invoiceManagement.models.invoice.invoice_path),
        ),
    ]
