# Generated by Django 3.0.4 on 2020-06-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceManagement', '0005_auto_20200613_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeOfInvoice',
            fields=[
                ('typeID', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(default='Undefined', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceAttachment',
            field=models.FileField(upload_to=''),
        ),
    ]
