# Generated by Django 3.0.4 on 2020-05-26 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectManagement', '0004_auto_20200423_1920'),
        ('invoiceManagement', '0002_auto_20200526_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('vendorID', models.AutoField(primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=50)),
                ('vendorOwner', models.CharField(max_length=50)),
                ('vendorCategory', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='projectExpense',
            fields=[
                ('expenseID', models.AutoField(primary_key=True, serialize=False)),
                ('expenseAmount', models.IntegerField()),
                ('expenseReceipient', models.CharField(default=' ', max_length=40)),
                ('expenseType', models.CharField(default='', max_length=50)),
                ('expenseDate', models.DateField()),
                ('expenseDetails', models.TextField(max_length=300)),
                ('expenseAttachment', models.ImageField(default='', upload_to='expenses/images')),
                ('expenseExtraWorkBoolean', models.CharField(default='False', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projectManagement.project')),
                ('projectSourceInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectSourceInvoice', to='invoiceManagement.invoice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='accountManagement.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='operatingExpense',
            fields=[
                ('expenseID', models.AutoField(primary_key=True, serialize=False)),
                ('expenseAmount', models.IntegerField()),
                ('expenseReceipient', models.CharField(default=' ', max_length=40)),
                ('expenseType', models.CharField(default='', max_length=50)),
                ('expenseDate', models.DateField()),
                ('expenseDetails', models.TextField(max_length=300)),
                ('expenseAttachment', models.ImageField(default='', upload_to='expenses/images')),
                ('expenseExtraWorkBoolean', models.CharField(default='False', max_length=10)),
                ('operatingSourceInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatingSourceInvoice', to='invoiceManagement.invoice')),
            ],
        ),
    ]
