# Generated by Django 3.0.4 on 2020-06-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectexpense',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='operatingexpense',
            name='expenseDetails',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='expenseDetails',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='expenseExtraWorkBoolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='expenseReceipient',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='expenseType',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorCategory',
            field=models.CharField(max_length=60),
        ),
    ]
