# Generated by Django 3.0.4 on 2020-06-13 02:11

import accountManagement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0004_auto_20200423_1920'),
        ('accountManagement', '0003_auto_20200608_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendorExpense',
            fields=[
                ('expenseID', models.AutoField(primary_key=True, serialize=False)),
                ('expenseAmount', models.IntegerField()),
                ('expenseReceipient', models.CharField(default='Not Found', max_length=50)),
                ('expenseType', models.CharField(default='', max_length=50)),
                ('expenseDate', models.DateField()),
                ('expenseDetails', models.TextField()),
                ('expenseAttachment', models.FilePathField(default='File not uploaded at entry', path=accountManagement.models.vendorExpense.vendorExpense_path)),
                ('expenseExtraWorkBoolean', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendorExpenseProject', to='projectManagement.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='generalexpense',
            name='projectSourceInvoice',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendorAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='expenseAttachment',
            field=models.FilePathField(default='File not uploaded at entry', path=accountManagement.models.generalExpense.generalExpense_path),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='expenseDetails',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='expenseReceipient',
            field=models.CharField(default='Not Found', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='expenseType',
            field=models.CharField(default='Not Found', max_length=40),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalExpenseProject', to='projectManagement.project'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorCategory',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='operatingExpense',
        ),
        migrations.AddField(
            model_name='vendorexpense',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='accountManagement.vendor'),
        ),
    ]
