# Generated by Django 3.0.4 on 2020-06-13 02:27

import accountManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0004_auto_20200613_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalexpense',
            name='expenseAttachment',
            field=models.FilePathField(blank=True, default='File not uploaded at entry', path=accountManagement.models.generalExpense.generalExpense_path),
        ),
        migrations.AlterField(
            model_name='vendorexpense',
            name='expenseAttachment',
            field=models.FilePathField(blank=True, default='File not uploaded at entry', path=accountManagement.models.vendorExpense.vendorExpense_path),
        ),
    ]
