# Generated by Django 3.0.4 on 2020-06-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorManagement', '0001_initial'),
        ('accountManagement', '0005_auto_20200613_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorexpense',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='vendorManagement.vendor'),
        ),
        migrations.DeleteModel(
            name='vendor',
        ),
    ]
