# Generated by Django 3.0.4 on 2020-06-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0006_auto_20200613_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorexpense',
            name='expensePaid',
            field=models.BooleanField(default=True),
        ),
    ]
