# Generated by Django 3.0.4 on 2020-06-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0007_vendorexpense_expensepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalexpense',
            name='expenseAttachment',
            field=models.FileField(upload_to=''),
        ),
    ]
