# Generated by Django 3.0.4 on 2020-06-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0008_auto_20200615_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorexpense',
            name='expenseReceipient',
        ),
    ]
