# Generated by Django 3.0.4 on 2020-06-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('vendorID', models.AutoField(primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=50)),
                ('vendorOwner', models.CharField(max_length=50)),
                ('vendorCategory', models.CharField(max_length=50)),
                ('vendorAmount', models.IntegerField()),
            ],
        ),
    ]
